<a href="https://colab.research.google.com/github/SzymonParszewski/data-sciece-bootcamp/blob/master/Intro4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print('Hello Collab')

Hello Collab


Podstawy

In [2]:
import numpy as np
np.__version__

'1.17.5'

In [0]:
print(dir(np))

In [0]:
help(np.array)

1D RAY

In [0]:
x=np.array([1,3])
x

array([1, 3])

In [0]:
type(x)

numpy.ndarray

In [0]:
x.ndim

1

In [0]:
x.shape

(2,)

In [0]:
x.size

2

In [0]:
x.dtype

dtype('int64')

2D Array

In [0]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [0]:
x.ndim

2

In [0]:
x.shape

(2, 2)

In [0]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [0]:
x.shape

(2, 3)

In [0]:
x.ndim

2

3D Ray

In [0]:
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(x)

In [0]:
x.ndim

3

Typy danych

In [0]:
A=np.array([[1.3,2.2,3.1],[1.6,2.4,3.2]],dtype=complex)
print(A)

[[1.3+0.j 2.2+0.j 3.1+0.j]
 [1.6+0.j 2.4+0.j 3.2+0.j]]


In [0]:
A.dtype

dtype('complex128')

Tworzenie tablic

In [0]:
x=np.zeros(shape=(4,10),dtype=int)
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [0]:
x=np.ones(shape=(4,10),dtype=int)
print(x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [0]:
x=np.full(shape=(4,10),fill_value=4,dtype=int)
print(x)

[[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]


In [0]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x=np.arange(start=10,stop=100, step=5)
print(x)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [0]:
x=np.linspace(start=10,stop=1000, num=5)
print(x)

[  10.   257.5  505.   752.5 1000. ]


In [0]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Podstawowe operacje na tablicach

In [0]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
print(A)
print(B)

[1 2 3 4]
[5 6 7 8]


In [0]:
B-A

array([4, 4, 4, 4])

In [0]:
A+B

array([ 6,  8, 10, 12])

In [0]:
A**B

array([    1,    64,  2187, 65536])

In [0]:
A/B

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [0]:
np.add(A,B)

array([ 6,  8, 10, 12])

In [0]:
np.subtract(A,B)

array([-4, -4, -4, -4])

In [0]:
np.multiply(A,B)

array([ 5, 12, 21, 32])

In [0]:
np.divide(A,B)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [0]:
A=np.array([[1,2],[5,6]])
B=np.array([[5,6],[5,3]])
print(A,'\n')
print(B)

[[1 2]
 [5 6]] 

[[5 6]
 [5 3]]


In [0]:
A.dot(B)

array([[15, 12],
       [55, 48]])

Generowanie liczb pseudolosowych

In [0]:
np.random.seed(0)

In [0]:
np.random.randn() #%%losowy rozkład normalny

0.9787379841057392

In [0]:
np.random.randn(10) #%% tablica składająca się z 10 losowo wylosowanych liczb

array([ 2.2408932 ,  1.86755799, -0.97727788,  0.95008842, -0.15135721,
       -0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  0.76103773])

In [0]:
np.random.randn(4,10)

In [0]:
np.random.rand()

0.8209932298479351

In [0]:
np.random.rand(10)

array([0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ,
       0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696])

In [0]:
np.random.randint(low=12, high=120,size=10) #%%losowa liczba dwucyfrowa większa od low i mniejsza od high

array([ 51,  55,  51, 112,  99, 114,  92,  63, 108,  98])

In [0]:
np.random.choice([1,2,3,4,5,67,8])

4

In [0]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.random.shuffle(data)
data

array([6, 3, 0, 1, 8, 4, 2, 5, 7, 9])

Podstawowe funkcje w bibliotece NumPy

In [0]:
np.exp(1)

2.718281828459045

In [0]:
np.sqrt(4)

2.0

In [0]:
np.all([1,2,3,0]) #%%funkcja zwraca nam wartość logiczną wszystkich argumentów

False

In [0]:
np.any([0,0,0,1]) #%%Funkcja zwraca czy jakikolwiek element jest prawdą

True

In [0]:
A=np.random.rand(5)
A

array([0.69337635, 0.36779075, 0.02918147, 0.13085877, 0.84154185])

In [0]:
np.argmax(A)

4

In [0]:
A[np.argmax(A)]

0.8415418529195402

In [0]:
np.argsort(A) #%%sortuje po indeksie od najmniejszej wartości do największej

array([2, 3, 1, 0, 4])

Indeksowanie, Wycinanie

In [0]:
B=np.arange(20)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Iteracja po tablicach, zmiana rozmiaru oraz maski logiczne

In [0]:
for item in B.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [0]:
for row in B:
  print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [0]:
B.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [0]:
B.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
B.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [0]:
B.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Maski logiczne

In [0]:
C=np.arange(start=-10,stop=10,step=0.5)
C.reshape(10,-1)
C

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [0]:
C[np.bitwise_and(C>0,C<5)]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Podstawy algebry.
Norma wektora, równanie wektora w R2

In [3]:
v1=np.array([0,4])
v1

array([0, 4])

In [4]:
np.linalg.norm(v1) #%% długość wektora v1

4.0

Norma euklidesowa Rn

In [5]:
v2=np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [6]:
p=np.array([3,0])
q=np.array([0,4])
np.linalg.norm(p-q)

5.0

Odległość dwóch punktów w przestrzeni Rn

In [7]:
p=np.array([3,0,1])
q=np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

In [11]:
X=np.array([[5,3],[3,9]])
Y=np.array([[1],[-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [14]:
Z=np.dot(X,Y)
Z

array([[ 2],
       [-6]])

Przykład 2

In [15]:
X=np.array([[2,-1,3],[3,1,0]])
Y=np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [17]:
Z=np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy, macierz jednostkowa, odwrotna i transponowana

Wyznacznik macierzy

In [19]:
A=np.array([[1,3],[4,7]])
np.linalg.det(A)

-4.999999999999999

Ślad macierzy-suma tego co mamy na przekątnej

In [20]:
A=np.array([[1,3],[4,7]])
np.trace(A)

8

Macierz jednostkowa

In [21]:
np.eye(10,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

Macierz odwrotna

In [22]:
A

array([[1, 3],
       [4, 7]])

In [23]:
B=np.linalg.inv(A)
B

array([[-1.4,  0.6],
       [ 0.8, -0.2]])

In [25]:
np.set_printoptions(precision=4,suppress=True)
np.dot(A,B)

array([[ 1.,  0.],
       [-0.,  1.]])

Macierz transponowana

In [26]:
A.T

array([[1, 4],
       [3, 7]])

Układ równań

2x+4y=10
x-y=-1

In [30]:
W=np.array([[2,4],[1,-1]])
Z=np.array([[10],[-1]])
print(W,'\n')
print(Z)

[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [31]:
W_odwr=np.linalg.inv(W)
X=np.dot(W_odwr,Z)
X

array([[1.],
       [2.]])

In [32]:
W.shape

(2, 2)

In [33]:
X = np.array([2., -3, 4])
print(X.dtype)

float64
