<a href="https://colab.research.google.com/github/SzymonParszewski/data-sciece-bootcamp/blob/master/Intro1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello Collab')

Hello Collab


Podstawy

In [2]:
import numpy as np
np.__version__

'1.17.5'

In [0]:
print(dir(np))

In [0]:
help(np.array)

1D RAY

In [8]:
x=np.array([1,3])
x

array([1, 3])

In [9]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

2D Array

In [16]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [20]:
x.shape

(2, 3)

In [21]:
x.ndim

2

3D Ray

In [0]:
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(x)

In [25]:
x.ndim

3

Typy danych

In [35]:
A=np.array([[1.3,2.2,3.1],[1.6,2.4,3.2]],dtype=complex)
print(A)

[[1.3+0.j 2.2+0.j 3.1+0.j]
 [1.6+0.j 2.4+0.j 3.2+0.j]]


In [36]:
A.dtype

dtype('complex128')

Tworzenie tablic

In [38]:
x=np.zeros(shape=(4,10),dtype=int)
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [39]:
x=np.ones(shape=(4,10),dtype=int)
print(x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [40]:
x=np.full(shape=(4,10),fill_value=4,dtype=int)
print(x)

[[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]


In [43]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x=np.arange(start=10,stop=100, step=5)
print(x)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [46]:
x=np.linspace(start=10,stop=1000, num=5)
print(x)

[  10.   257.5  505.   752.5 1000. ]


In [47]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Podstawowe operacje na tablicach

In [51]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
print(A)
print(B)

[1 2 3 4]
[5 6 7 8]


In [52]:
B-A

array([4, 4, 4, 4])

In [53]:
A+B

array([ 6,  8, 10, 12])

In [54]:
A**B

array([    1,    64,  2187, 65536])

In [55]:
A/B

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [56]:
np.add(A,B)

array([ 6,  8, 10, 12])

In [57]:
np.subtract(A,B)

array([-4, -4, -4, -4])

In [58]:
np.multiply(A,B)

array([ 5, 12, 21, 32])

In [59]:
np.divide(A,B)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [63]:
A=np.array([[1,2],[5,6]])
B=np.array([[5,6],[5,3]])
print(A,'\n')
print(B)

[[1 2]
 [5 6]] 

[[5 6]
 [5 3]]


In [64]:
A.dot(B)

array([[15, 12],
       [55, 48]])

Generowanie liczb pseudolosowych